services:
    web:
        container_name: "php53"
        build:
            context: ./php53
        ports:
            - "8053:80"
        depends_on:
          - db
        volumes:
            - "/mnt/d/docker/www:/usr/local/apache2/htdocs/"
    web2:
        container_name: "php82"
        build:
            context: ./php82
        ports:
            - "8080:80"
        depends_on:
            - db
        volumes:
            - "/mnt/d/docker/www:/var/www/html/"
    db:
        container_name: mysql5651
        image: mysql:5.6.51
        ports: 
            - "3308:3306"
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
            MYSQL_ROOT_PASSWORD: example
            # MYSQL_ROOT_PASSWORD: 12345678
            # MYSQL_DATABASE: smdb
            # MYSQL_USER: mydbuser
            # MYSQL_PASSWORD: 12345678
        restart: always
        volumes:
            - /mnt/d/docker/mysql:/var/lib/mysql/