version: '3.8'
services:
    web:
        container_name: "php53"
        build:
            context: ./php53
        ports:
            - '8053:80'
        depends_on:
          - db
        # volumes:
        #     - /mnt/d/docker/www:/usr/local/apache2/htdocs/
    web2:
        container_name: "php82"
        build:
            context: ./php82
        ports:
            - '8080:80'
        depends_on:
            - db
        # volumes:
        #     - /mnt/d/docker/www:/var/www/html/
    db:
        container_name: mysql5744
        image: mysql:5.7.44
        # command: [--default-authentication-plugin=mysql_native_password]
        environment:
            MYSQL_ROOT_PASSWORD: example
            # MYSQL_ROOT_PASSWORD: 12345678
            # MYSQL_DATABASE: smdb
            # MYSQL_USER: mydbuser
            # MYSQL_PASSWORD: 12345678
        ports: 
            - '3306:3306'
    #     volumes:
    #         - mysql_data_test:/var/lib/mysql/
    # volumes:
    #     mysql_data_test: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
    #         driver: local